### ISSUE TITLE
tensorflow version

### ISSUE THREAD

**Issue by rednaks** [JRMeyer/tensorflow-tutorial#4]
Can I know which tensorflow version was used in this tutorial ?
It seems that now `pip install tensorflow` is installing the latest version (1.0) and this broke the code.

I could try to update the code later to support 1.0 if you're interested :)

Thanks.

**Comment by JRMeyer** [comment]
Salut Alexandre!

It looks like this code / tutorial was written with version 0.6.0.

Atleast, that's the version I have installed right now:

```
josh@yoga:~/Bureau$ python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
>>> tensorflow.__version__
'0.6.0'
```

If you'd like to update the code I would be very happy!

Let me know if you have issues, and I'll try to help.

I'd be better at maintaining this code, but I'm spending more time on speech tech (ASR, TTS) than NLP at the moment:/

Any help would be much appreciated!

-josh

**Comment by JRMeyer** [comment]
updated to 1.0 a while ago, forgot to close issue

**Comment by masterchop** [comment]
I tested with 1.13 and works out of the box, my own data set fails :(
